name: Code Review Workflow

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      
      - name: Run linting
        run: npm run lint
        continue-on-error: true  #continue even if linting fails to ensure other checks are runningg

      - name: Run code quality analysis
        run: npm run analyze
        continue-on-error: true  

      - name: Scan for vulnerabilities
        run: npm audit

      #commenting on the pull request with the results of code review
      - name: Comment on pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueComment = `
            Thank you for the pull request! Here's the summary of the code review:
            - Linting: ${{ job.status }}
            - Code quality analysis: ${{ job.status }}
            - Security vulnerabilities: ${{ job.status }}
            `;

            github.issues.createComment({
              issue_number: pullRequest.numberr,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Code review checks have been completed.'
            });
