name: Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        run: |
          echo "Generating release notes..."
          # Fetch the commit messages since the last release and save them to a file
          git log --pretty=format:"%s" > ./release_notes.txt

      - name: Make Commits
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Display Commit Logs"
          git push origin main

      - name: Upload Release Notes as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release_notes.txt
