name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * *'  

jobs:
  dependency-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install Dependabot
        run: npm install -g dependabot

      - name: Run Dependabot
        run: dependabot
