name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Heroku CLI
        uses: akhileshns/heroku-cli-action@v2.315.0

      - name: Login to Heroku
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | heroku login --interactive

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          git push heroku main:main
