name: Documentation Generation

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JSDoc and jsdoc-to-markdown
        run: npm install --save-dev jsdoc-to-markdown

      - name: Generate documentation
        run: |
          npx jsdoc-to-markdown ./src/utils.js > ./documentation.md

      - name: Check for changes and commit
        run: |
          if git diff --quiet; then
            echo "No changes to commit. Exiting..."
            exit 0
          fi
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Generate documentation"

      - name: Pull changes from main branch
        run: git pull origin main

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }} 
          branch: main   
