name: Scheduled Tasks

on:
  push:
    branches:
      - main

jobs:
  scheduled-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run maintenance tasks
        run: |
          npm install   
          npm test      
          echo "Running scheduled maintenance task"
